#**Data types and structures Questions**

**Ques 1.What are data structures, and why are they important?**

 **ans->**Data structures are ways to organize and store data in computers so it can be used efficiently. They are important because they help in managing large amounts of data, make programs faster, and are essential for writing efficient algorithms.

**Ques 2.  Explain the difference between mutable and immutable data types with examples.**

**ans->Difference Between Mutable and Immutable Data Types**

Mutable data types are those whose values can be changed after creation.

Immutable data types are those whose values cannot be changed once they are created. If you try to modify them, a new object is created.

Examples:
Mutable:
Types: list, dict, set

In [ ]:
my_list = [1, 2, 3]
my_list.append(4)  # The list is modified
my_list

[1, 2, 3, 4]

Immutable:Types: str,tuple

In [ ]:
name = "Sahil"
name[0]="i" #the str is immutable
name

TypeError: 'str' object does not support item assignment

**Ques 3.What are the main differences between lists and tuples in Python?**

**ans->** Main difference between List and Tuple

---
**List:**

1. Mutability- mutable(can be changed)
2. Syntax-define using[] brackets
3. Performance-slower(more flexible)

**Tuple:**
1.  Mutability- Immutable(can not be changed)
2.  Syantax-defined using () brackets
3.  Performance-Faster(less flexible)

**Ques 4. Describe how dictionaries store data?**

**ans->**Dictionaries store data in key-value pairs. Each key is unique and is used to access its associated value. Internally, Python uses a hash table to store these pairs, which allows for fast lookups.

In [ ]:
student = {"name": "Sahil", "age": 15, "grade": "10th"}
student

{'name': 'Sahil', 'age': 15, 'grade': '10th'}

**Ques 5. Why might you use a set instead of a list in Python?**

**ans->**A set is an unordered collection of unique elements, while a list is an ordered collection that can contain duplicate elements. You might prefer using a set over a list in the following cases:

**To Ensure Uniqueness:**
Sets automatically eliminate duplicate values. This is useful when you want to store only distinct elements without manually checking for duplicates.

**Faster Membership Testing:**
Sets provide faster performance for checking whether an element exists (using hashing), typically in constant time O(1), whereas lists take linear time O(n).

**Use of Set Operations:**
Sets support mathematical operations like union, intersection, difference, and symmetric difference, which are not directly available with lists.

**Improved Performance in Certain Tasks:**
For large collections of data where order is not important and duplicates are not allowed, sets can be more efficient in terms of both speed and memory.

**Ques 6.What is a string in Python, and how is it different from a list?**

**ans->**In Python, a string is a sequence of characters used to represent textual data. It is enclosed within single quotes (' '), double quotes (" "), or triple quotes (''' ''' / """ """). Strings are immutable, meaning once a string is created, its contents cannot be changed.

Example:

In [ ]:
name ="Rohan"
name

'Rohan'

In [ ]:
type(name)

str

**Key Differences Between String and List:**

**Definition:**
A string is a sequence of characters used to represent text, whereas a list is a collection of elements that can be of any data type, such as numbers, strings, or even other lists.

**Mutability:**
Strings are immutable, meaning you cannot change the characters of a string after it is created. Lists are mutable, so you can modify, add, or remove elements.

**Data Type:**
A string contains only characters, while a list can contain elements of multiple data types, including integers, strings, and even other lists.

**Syntax:**
Strings are written using quotes (single ' ', double " ", or triple ''' '''), while lists are written using square brackets [ ].

**Ques 7. How do tuples ensure data integrity in Python?**

**ans->**In Python, tuples are immutable, meaning their values cannot be changed, added to, or removed after creation. This immutability ensures data integrity by preventing accidental or intentional modifications to the data.

**Key Points:**
Immutability:
Once a tuple is created, its contents are fixed. This guarantees that the data remains constant throughout the program.

**Protection from Modification:**
Since you cannot change elements of a tuple, it protects the original data from being altered, which is especially important when the data is sensitive or critical.

**Safe to Use as Dictionary Keys:**
Because they are immutable, tuples can be used as keys in dictionaries—something mutable types like lists cannot do. This allows for reliable and consistent access to data.

**Ques 8.What is a hash table, and how does it relate to dictionaries in Python?**

**ans->A hash table** is a data structure that stores data in key-value pairs and uses a hash function to compute an index (or hash code) where the value should be stored. This allows for fast data retrieval, insertion, and deletion — usually in constant time O(1).

Relation to Dictionaries in Python:
In Python, a dictionary is an implementation of a hash table.

->Keys in a dictionary are passed through a hash function to determine their location in memory.

->This enables quick access to values using keys, without needing to search through the entire collection.

**Ques 9. Can lists contain different data types in Python?**

**ans->**Yes, lists in Python can contain different data types. Python lists are heterogeneous, meaning a single list can store elements like integers, strings, floats, booleans, or even other lists and objects.

In [ ]:
mixed_list = [10, "Hello", 3.14, True, [1, 2, 3]]
mixed_list

[10, 'Hello', 3.14, True, [1, 2, 3]]

**Ques 10.Explain why strings are immutable in Python?**

**ans->**Strings are immutable in Python, meaning once a string is created, it cannot be changed. Any operation that seems to modify a string actually creates a new string object.

**Reasons Why Strings Are Immutable:**
->Security and Reliability:
Since strings are often used as keys in dictionaries or for storing sensitive data (like file paths or URLs), immutability ensures they remain unchanged throughout the program.

->Hashing:
Immutable objects can be hashed, which is required when using strings as dictionary keys or elements in sets.

->Memory Efficiency:
Python uses a technique called string interning to save memory. Immutability allows sharing the same string object in multiple places.

->Thread Safety:
In multi-threaded environments, immutable objects like strings avoid issues caused by shared data being modified by different threads.

**Ques 11. What advantages do dictionaries offer over lists for certain tasks?**

**ans->**Dictionaries offer several key advantages over lists when working with key-value data or when fast lookups are required.

**Advantages of Dictionaries Over Lists:**

**Fast Lookups:**
Dictionaries use hash tables, allowing you to access values in constant time (O(1)) using keys.


**Key-Value Pair Storage:**
Dictionaries store data in key-value pairs, making them ideal for situations where you want to label or describe your data.

**Improved Readability and Organization:**Dictionaries make the code more descriptive and readable, especially when the data has meaningful names.

In [ ]:
# Using a dictionary
student = {"name": "Sahil", "age": 15}

# Using a list
student = ["Sahil", 15]  # Less clear

**Ques 12. Describe a scenario where using a tuple would be preferable over a list?**

**ans->**A tuple is preferable over a list when you want to store fixed, constant data that should not be modified during the program.

**Example Scenario:**
Suppose you're storing the coordinates of a location (like latitude and longitude) in a program:

In [ ]:
coordinates = (28.6139, 77.2090)  # Tuple

In this case:

->The coordinates are fixed values.

->You don’t want anyone (or any part of your code) to accidentally change them.

->A tuple ensures data integrity by being immutable

**Ques 13. How do sets handle duplicate values in Python?**

**ans->**In Python, sets automatically remove duplicate values. When you create a set, it only stores unique elements, even if duplicates are included during creation.

**How It Works:**

->Sets are unordered collections of unique items.

->If you add the same value multiple times, the set will keep only one copy of that value.

In [ ]:
my_set = {1, 2, 2, 3, 4, 4, 4}
print(my_set)  # Output: {1, 2, 3, 4}

{1, 2, 3, 4}

Even though 2 and 4 were added multiple times, the set contains each of them only once.

**Ques 14.How does the “in” keyword work differently for lists and dictionaries?**

**ans->**The in keyword is used to check if an item exists in a collection like a list, dictionary, tuple, or set. It returns True if the item is found and False if not.

**How in Works in a List:**

When used with a list, in checks if a value is present in that list.

Example:

In [2]:
colors = ["red", "blue", "green"]
print("red" in colors)   #  True → "red" is in the list
print("yellow" in colors)  #  False → "yellow" is not in the list

True
False



* It looks through all the items in the list.


* If it finds the value, it returns True.

**How it works for Dictionaries:**

In a dictionary, in checks whether a given key exists in the dictionary.
It does not check for values directly.

In [1]:
student = {'name': 'Rohan', 'age': 22, 'grade': 'B.Tech'}

print('name' in student)  #  True
print('Suhani' in student)  #  False (Because it's a value, not a key)

True
False

**Ques 15. Can you modify the elements of a tuple? Explain why or why not?**

**ans->** No, you cannot modify the elements of a tuple in Python.

Because tuples are immutable.
'Immutability' means once a tuple is created, its elements cannot be changed, added, or removed.

In [ ]:
my_tuple = (10, 20, 30)
my_tuple[1] = 99    # This will cause an error

TypeError: 'tuple' object does not support item assignment

**Ques 16.What is a nested dictionary, and give an example of its use case?**

**ans->**A nested dictionary in Python is a dictionary inside another dictionary.

It means the values of a dictionary can themselves be dictionaries.

In [3]:
students = {
    "101": {
        "name": "Rohan",
        "age": 22,
        "grade": "10th"
    },
    "102": {
        "name": "Priyanka",
        "age": 21,
        "grade": "10th"
    }
}
students

{'101': {'name': 'Rohan', 'age': 22, 'grade': '10th'},
 '102': {'name': 'Priyanka', 'age': 21, 'grade': '10th'}}

Use Cases of Nested Dictionaries:
School records,employee Management,Country Data,product Catalogs

**Ques 17. Describe the time complexity of accessing elements in a dictionary?**

**ans->** The time complexity of accessing an element in a dictionary is:

->Average Case: O(1) (Constant time)

-> Worst Case: O(n) (Very rare)

Explanation:
Python dictionaries are implemented using a data structure called a hash table. Here's how it works:

->Step-by-step:

1.Key is hashed (converted to a number using hash()).

2.This hash is used to calculate an index.

3.The value is retrieved directly from that index.

Because of this, accessing a value using a key is very fast — it doesn’t need to go through every element like a list.

In [ ]:
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(my_dict['b'])  # O(1)

2

**Ques 18. In what situations are lists preferred over dictionaries?**

**ans->Lists are preferred over dictionaries in situations where:**

1. Order Matters:

->Lists maintain the order of elements as they are inserted.

-> Useful when sequence or indexing is important.

Example:

In [ ]:
tasks = ["wake up", "brush teeth", "study", "sleep"]
print(tasks[2])  # Output: study

study

2. You only need values (not key-value pairs):

->When there's no need to label data with keys.

->If you're storing just a collection of items, a list is simpler and uses less memory.

Example:

In [ ]:
fruits = ["apple", "banana", "mango"]  # Simple and readable
fruits

['apple', 'banana', 'mango']

3. You need to maintain duplicates:

->Lists allow duplicate values, dictionaries do not allow duplicate keys.

Example:

In [ ]:
marks = [85, 90, 85, 92]  # Allowed in list
marks

[85, 90, 85, 92]

 5. Sorting elements:

->Lists can be easily sorted using .sort() or sorted().

Example:

In [ ]:
numbers = [3, 1, 4, 2]
numbers.sort()
print(numbers)  # Output: [1, 2, 3, 4]

[1, 2, 3, 4]


**Ques 19.Why are dictionaries considered unordered, and how does that affect data retrieval?**

**ans->** Why were dictionaries considered unordered?


*   Dictionaries use a hash table to store key-value pairs.
*   This structure is optimized for quick access using keys, not for maintaining order.

* The location of each key-value pair in memory depends on the hash value of the key, not on when or where it was added.

**Effect on Data Retrieval:**


*   You could not rely on the order of items.
*  Two dictionaries with the same items might show them in different orders when printed or iterated.
*  we access values using keys, not indexes like lists.

**Ques 20. Explain the difference between a list and a dictionary in terms of data retrieval.**

**ans->The main difference between a list and a dictionary in terms of data retrieval lies in how elements are accessed:**

**-> List: Index-Based Retrieval:**


1.   In a list, elements are accessed by their position (index).
2.  Indexes start from 0.

3.  Retrieval is position-dependent.
4. Time Complexity:
Access by index:O(1) (very fast)

Example:

In [ ]:
my_list = ['apple', 'banana', 'mango']
print(my_list[1])   # Output: banana

banana

**Dictionary: Key-Based Retrieval:**



1. In a dictionary, elements are
accessed using a Key.  
2.  Keys are unique, and each key maps to a specific value.

3. Retrieval is label-based, not position-based.

4.Time Complexity:
Access by key: O(1) (average case, very fast)



Example:

In [ ]:
my_dict = {'fruit1': 'apple', 'fruit2': 'banana'}
print(my_dict['fruit2'])   # Output: banana

banana

# **Practical Questions**

**Ques 1.Write a code to create a string with your name and print it.**

**ans->**

In [ ]:
my_name="Rohan" # create aa string with your name
print("my name is :",my_name) #print the name

my name is : Rohan

**Ques 2.Write a code to find the length of the string "Hello World"?**

**ans->**

In [ ]:
string_1="Hello World" # define the string
length=len(string_1) # find length using len() function
print("the length of the string:",length) #print  the result

the length of the string: 11

**Ques 3. Write a code to slice the first 3 characters from the string "Python Programming".**

**ans->**

In [ ]:
text="Python Programming" # define the string
first_three=text[0:3] #slice the first three characters
print("the first three characters:",first_three)

the first three characters: Pyt

**Ques 4.Write a code to convert the string "hello" to uppercase.**

**ans->**

In [ ]:
# Define the string
text = "hello"

# Convert to uppercase using upper() method
uppercase_text = text.upper()

# Print the result
print("Uppercase version:", uppercase_text)

Uppercase version: HELLO

**Ques 5. Write a code to replace the word "apple" with "orange" in the string "I like apple".**

**ans->**

In [ ]:
string="I like apple" #define the string
new_text=string.replace("apple","orange")# replace "apple" with "orange"
print("updated string:",new_text) #print the result

updated string: I like orange

**Ques 6.Write a code to create a list with numbers 1 to 5 and print it.**

**ans->**

In [ ]:
numbers=[1,2,3,4,5] # create a list with numbers 1 to 5
print("the list is:",numbers) # print the list

the list is: [1, 2, 3, 4, 5]

**Ques 7.Write a code to append the number 10 to the list [1, 2, 3, 4].**

**ans->**

In [ ]:
list_1=[1,2,3,4]# create a list
list_1.append(10) # append the number 10
print("Updated list:",list_1)

Updated list: [1, 2, 3, 4, 10]

**Ques 8.Write a code to remove the number 3 from the list [1, 2, 3, 4, 5].**

**ans->**

In [ ]:
list_2=[1,2,3,4,5] #create a list
list_2.remove(3)# remove the number 3 from the list_2
print("the updated list:",list_2)# print the result

the updated list: [1, 2, 4, 5]

**Ques 9.Write a code to access the second element in the list ['a', 'b', 'c', 'd'].**

**ans->**

In [ ]:
list_3=['a','b','c','d'] # create a list
second_element=list_3[1] # use list index to access the element
print("the second element of the list is:",second_element)# print the result

the second element of the list is: b

**Ques 10. Write a code to reverse the list [10, 20, 30, 40, 50].**

**ans->**

In [ ]:
number=[10,20,30,40,50] #create a list
list_rev=number[::-1] # to reverse the original list
print("the reverse list is:",list_rev)# print the result

the reverse list is: [50, 40, 30, 20, 10]

**Ques 11. Write a code to create a tuple with the elements 100, 200, 300 and print it.**

**ans->**

In [ ]:
tuple_1=(100,200,300) # create a tuple
print(tuple_1) # print the tuple

(100, 200, 300)

**Ques 12.Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').**

**ans->**

In [ ]:
tuple_2=('red','green','blue','yellow')# create a tuple
second_last=tuple_2[1:]# apply list slicing
print("the second to last element of the tuple:",second_last)# print the result

the second to last element of the tuple: ('green', 'blue', 'yellow')

**Ques 13. Write a code to find the minimum number in the tuple (10, 20, 5, 15).**

**ans->**

In [ ]:
t=(10,20,5,15) # create a tuple
minimum=min(t) # find the minimum using min()
print("minimum number is:",minimum)# print the result

minimum number is: 5

**Ques 14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').**

**ans->**

In [ ]:
# Define the tuple
animals = ('dog', 'cat', 'rabbit')

# Find the index of 'cat'
index_of_cat = animals.index('cat')

# Print the result
print("Index of 'cat' is:",index_of_cat)

Index of 'cat' is: 1

**Ques 15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.**

**ans->**

In [4]:
# Creating a tuple with three different fruits
fruits = ("apple", "banana", "mango")

# Checking if "kiwi" is in the tuple
if "kiwi" in fruits:
    print("Kiwi is in the tuple.")
else:
    print("Kiwi is not in the tuple.")

Kiwi is not in the tuple.

**Ques 16.Write a code to create a set with the elements 'a', 'b', 'c' and print it.**

**ans->**

In [5]:
my_set={'a','b','c'} #creating a set with elements a,b,c
print(my_set) # printing the set

{'a', 'b', 'c'}

**Ques 17.Write a code to clear all elements from the set {1, 2, 3, 4, 5}.**

**ans->**

In [9]:
set_1={1,2,3,4,5} # creating a set
set_1.clear()# clearing all elements from the list
print(set_1) # printing the clear set

set()

**Ques 18. Write a code to remove the element 4 from the set {1, 2, 3, 4}.**

**ans->**

In [10]:

my_set = {1, 2, 3, 4}# Creating the set
my_set.remove(4)# Removing the element 4
print(my_set)# Printing the updated set

{1, 2, 3}

**Ques 19.Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.**

**ans->**

In [11]:
# Creating two sets
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Finding the union of the two sets
union_set = set1.union(set2)

# Printing the union
print(union_set)

{1, 2, 3, 4, 5}

**Ques 20.Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.**

**ans->**

In [13]:
# Creating two sets
set1 = {1, 2, 3}
set2 = {2, 3, 4}

# Finding the intersection of the two sets
intersection_set = set1.intersection(set2)

# Printing the intersection
print(intersection_set)

{2, 3}

**Ques 21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it.**
**ans->**

In [14]:
# Creating a dictionary
person = {
    "name": "Rohan",
    "age": 22,
    "city": "Aigarh"
}

# Printing the dictionary
print(person)

{'name': 'Rohan', 'age': 22, 'city': 'Aigarh'}

**Ques 22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}**

**ans->**

In [15]:
# Original dictionary
person = {'name': 'John', 'age': 25}

# Adding a new key-value pair
person['country'] = 'USA'

# Printing the updated dictionary
print(person)

{'name': 'John', 'age': 25, 'country': 'USA'}

**Ques 23.. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.**

**ans->**

In [18]:
person={'name':'Alice','age':30} # creating a dictionary
name=person['name'] # accessing the value of the key "name"
print(name) # printing the value

Alice

**Ques 24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.**

**ans->**

In [20]:
# Creating the dictionary
person = {'name': 'Bob', 'age': 22, 'city': 'New York'}

# Removing the key "age"
person.pop('age')

# Printing the updated dictionary
print(person)

{'name': 'Bob', 'city': 'New York'}

**Ques 25.Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.**

**ans->**

In [21]:
# Creating the dictionary
person = {'name': 'Alice', 'city': 'Paris'}

# Checking if the key "city" exists
if "city" in person:
    print("Key 'city' exists in the dictionary.")
else:
    print("Key 'city' does not exist in the dictionary.")

Key 'city' exists in the dictionary.

**Ques 26. Write a code to create a list, a tuple, and a dictionary, and print them all.**

**ans->**

In [22]:
# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a tuple
my_tuple = ('apple', 'banana', 'cherry')

# Creating a dictionary
my_dict = {'name': 'Rohan', 'age': 22, 'state':'Uttar pradesh'}

# Printing all of them
print("List:", my_list)
print("Tuple:", my_tuple)
print("Dictionary:", my_dict)

List: [1, 2, 3, 4, 5]
Tuple: ('apple', 'banana', 'cherry')
Dictionary: {'name': 'Rohan', 'age': 22, 'state': 'Uttar pradesh'}

**Ques 27.Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
result.(replaced)**

**ans->**

In [27]:
import random
# Create a list of 5 random numbers between 1 and 100
random_numbers = random.sample(range(1, 101), 5)

# Sort the list in ascending order
random_numbers.sort()

# Print the sorted list
print("Sorted random numbers:", random_numbers)

Sorted random numbers: [15, 40, 43, 63, 99]

**Ques 28. Write a code to create a list with strings and print the element at the third index**

**ans->**

In [28]:
# Creating a list of strings
my_list = ['apple', 'banana', 'cherry', 'date', 'elderberry']

# Printing the element at the third index
print("Element at index 3:", my_list[3])

Element at index 3: date

**Ques 29. Write a code to combine two dictionaries into one and print the result.**

**ans->**

In [29]:
# Creating two dictionaries
dict1 = {'name': 'Rohan', 'age': 22}
dict2 = {'city': 'aligarh','state':'Uttar Pradesh', 'country': 'India'}

# Combining the dictionaries
combined_dict = {**dict1, **dict2}

# Printing the combined dictionary
print("Combined Dictionary:", combined_dict)

Combined Dictionary: {'name': 'Rohan', 'age': 22, 'city': 'aligarh', 'state': 'Uttar Pradesh', 'country': 'India'}

**Ques 30. Write a code to convert a list of strings into a set.**

**ans->**

In [30]:
# List of strings
my_list = ['apple', 'banana', 'cherry', 'apple']

# Converting the list to a set
my_set = set(my_list)

# Printing the set
print(my_set)

{'banana', 'cherry', 'apple'}